name: CI
on:
  push:
    branches:
      - main
  pull_request:

# Automatically cancel previous workflow runs when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cargo-udeps
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-udeps

    - name: Install cargo-udeps
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-deny

    - name: Lint and test
      run: make ci
